# Generated by Django 3.2.5 on 2021-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my app', max_length=255),
        ),
    ]
